### ISSUE TITLE
Overlay component close button placement issue

### ISSUE THREAD

**Issue by sharvilak11** [e9ine/vue-components#2]
The component should have the close button on top-right of the content rather than top-right of the screen.
![Screenshot 2020-11-10 at 7 22 44 PM](https://user-images.githubusercontent.com/19903825/98682610-20578e00-238a-11eb-864d-0b72faa7a540.png)

**Comment by e9-skanthi** [comment]
Moved overlay close button inside overlay content for fixed overlays.
